### ISSUE TITLE
Installation error in Saas Manager Modification module (saas_manager_x)

### ISSUE THREAD

**Issue by jack-solutions** [ingadhoc/odoo-saas-manager#1]
I've successfully installed saas_manaer, saas_product_base_module, web_saas_cust.
but while installing saas_manager_x got an error:

Traceback (most recent call last):
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/mrugank/odoo-dev/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/mrugank/odoo-dev/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/addons/base/module/module.py", line 494, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/mrugank/odoo-dev/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/mrugank/odoo-dev/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/mrugank/odoo-dev/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/mrugank/odoo-dev/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/mrugank/odoo-dev/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/mrugank/odoo-dev/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/mrugank/odoo-dev/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/mrugank/odoo-dev/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/mrugank/odoo-dev/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/models.py", line 4077, in create
    record = self.browse(self._create(old_vals))
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/models.py", line 4268, in _create
    recs._validate_fields(vals)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `phone` does not exist

Error context:
View `saas_manager.instance.form`
[view_id: 683, xml_id: n/a, model: saas_manager.instance, parent_id: 552]" while parsing /home/mrugank/odoo-dev/odoo-saas-manager-master/addons/saas_manager_x/view/instance_view.xml:31, near
<record id="view_saas_instance_form" model="ir.ui.view">
            <field name="name">saas_manager.instance.form</field>
            <field name="model">saas_manager.instance</field>
            <field name="inherit_id" ref="saas_manager.view_saas_manager_instance_form"/>
            <field name="arch" type="xml">

```
            <sheet position="replace">
                <sheet string="Instance">      
                    <field name="pricelist_id" invisible="1"/>
                    <field name="fiscal_position" invisible="1"/>
                    <field name="currency_id" invisible="1"/>
                    <!-- We are not going to use image right now -->
                    <!-- <field name="image" widget="image" class="oe_left oe_avatar" options="{&quot;preview_image&quot;: &quot;image_medium&quot;, &quot;size&quot;: [90, 90]}"/> -->
                    <div class="oe_title">
                        <div class="oe_edit_only">
                            <label for="name"/>
                        </div>
                        <h1>
                            <field name="name" default_focus="1" placeholder="Name"/>
                        </h1>
                        <h2>
                            <field name="url" widget="url" attrs="{'invisible':[('state','!=','open')]}"/>
                        </h2>
                    </div>
                    <div class="oe_right oe_button_box" name="buttons">
                        <button name="update_users" states="open" type="object" string="Update Users"/>                               
                    </div>
                    <group col="4">
                        <!-- <field name="product_id"/> -->
                        <field name="partner_id" domain="[('is_company', '=', True)]" context="{'default_is_company': True, 'default_customer': 1}"/>
                        <field name="product_id" on_change="product_id_change(pricelist_id, product_id, partner_id, True, fiscal_position, context)"/>
                        <field name="tax_id" widget="many2many_tags" colspan="4"/>
                        <!-- We are not going to use image right now -->
                        <!--<field name="partner_id" domain="[('is_company', '=', True)]" context="{'default_is_company': True, 'default_customer': 1}" on_change="onchange_partner(partner_id)"/>-->
                        <field name="admin_name" groups="base.group_no_one"/>          
                        <field name="admin_pass" groups="base.group_no_one"/>
                        <field name="db_created"/>
                        <field name="product_free_periods"/>
                        <newline/>
                    </group>
                    <notebook>
                        <page string="Instance Lines">
                            <group col="4">
                                <field name="instance_user_ids" colspan="8">
                                    <tree editable="top">
                                        <field name="name"/>
                                        <field name="login"/>
                                        <field name="email"/>
                                        <field name="mobile"/>
                                        <field name="phone"/>
                                        <field name="active"/>
                                        <field name="remote_id" groups="base.group_no_one"/>
                                    </tree>
                            </field>
                                <group colspan="2" name="instance_sub_products">
                                    <field name="included_users_qty"/>
                                    <field name="additional_users"/>
                                    <field name="additional_user_price"/>
                                    <field name="amount_users"/>
                                    <field name="instance_additional_ids" context="{'product_id':product_id}"/>
                                </group>
                                <group class="oe_subtotal_footer oe_right" colspan="2" name="instance_total_total">
                                    <field name="amount_users" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                                    <field name="product_price" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                                    <field name="additional_ammount" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                                    <div class="oe_subtotal_footer_separator oe_inline" colspan="2"/>
                                    <!-- We dont use discount for now -->
                                    <field name="subtotal" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                                    <field name="discount"/>
                                    <field name="amount_untaxed" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                                    <field name="amount_tax" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                                    <div class="oe_subtotal_footer_separator oe_inline">
                                        <label for="amount_total"/>
                                        <button name="button_dummy" states="draft,sent" string="(update)" type="object" class="oe_edit_only oe_link"/>
                                    </div>
                                    <field name="amount_total" nolabel="1" class="oe_subtotal_footer_separator" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                                </group>
                            </group>
                        </page>
                        <page string="Periods">
                            <field name="instance_period_ids"/>
                        </page>
                    </notebook>
                </sheet>
            </sheet>
        </field>
    </record>
```

**Comment by jjscarafia** [comment]
Sorry, this project is depreciated, we are working in odoo-infrastructure project now, a bigger project than this one.
We keep this project alive because still there are some things we need to migrate to odoo infrastrscture. I will add a note on project home. 
Sorry!
